#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# integrations.py — wire the media stacks together over their own APIs.
#
#   ./integrations.py            (run by ./setup.sh; safe to run by hand)
#
# Everything here is "add it if it is missing": nothing that already exists is
# changed, so a setting you edit in an app's UI afterwards stays edited, and a
# re-run is a no-op. Each app is handled on its own — one that is not running,
# or fails, is reported and skipped, and the rest still get wired.
#
#   Transmission  download and incomplete dirs under /data/downloads
#   Plex          claimed to your account (asks for the code, when run by
#                 hand), then the Movies and TV libraries
#   Sonarr/Radarr root folder, Transmission as download client, Plex
#   Prowlarr      Byparr as Cloudflare proxy, Sonarr + Radarr as apps
#                 (fullSync: they get every indexer), Transmission, and the
#                 public indexers station runs
#   Bazarr        Sonarr + Radarr, English subtitles, free providers
#   Lingarr       Sonarr + Radarr (no languages: pick them in its UI)
#   Cleanuparr    account, authentik OIDC, Sonarr + Radarr + Transmission,
#                 queue cleaner and malware blocker
#   Kavita        admin account, Books library, authentik OIDC, and the API
#                 key books-glue uses
#   Shelfmark     Prowlarr + Transmission for torrents, Byparr, the CWA
#                 Library button, authentik OIDC
#   Calibre-Web   admin renamed to your login, which authentik's header logs
#                 you into
#   Home Assistant  owner account, trusts Traefik, history in MariaDB, MQTT
#
# The API keys are ours (arr/.env, generated by setup.sh and handed to the apps
# through their environment); the login is the one in authentik/.env. Apps are
# reached from this host at their container address on app-bridge, and point
# at each other by container name.
# ---------------------------------------------------------------------------
import base64
import hashlib
import http.cookiejar
import json
import os
import re
import secrets
import sqlite3
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

REPO = os.path.dirname(os.path.abspath(__file__))
NETWORK = os.environ.get("IRABELLE_NETWORK", "app-bridge")
TTY = sys.stdout.isatty()


def say(msg):
    print(f"\n\033[1m==>\033[0m {msg}" if TTY else f"\n==> {msg}", flush=True)


def note(msg):
    print(f"    {msg}", flush=True)


def warn(msg):
    print(f"\033[33m    WARN: {msg}\033[0m" if TTY else f"    WARN: {msg}", file=sys.stderr, flush=True)


# --- configuration ----------------------------------------------------------
def read_env(stack):
    """KEY=value lines of <stack>/.env, the same way setup.sh's env_var reads them."""
    out = {}
    path = os.path.join(REPO, stack, ".env")
    try:
        with open(path) as fh:
            for line in fh:
                m = re.match(r"\s*([A-Za-z0-9_]+)\s*=\s*(.*)$", line)
                if m:
                    out[m.group(1)] = m.group(2).split("#", 1)[0].strip().strip("\"'")
    except OSError:
        pass
    return out


def set_env(stack, key, value):
    """Set KEY=value in <stack>/.env, replacing the line if it is there."""
    path = os.path.join(REPO, stack, ".env")
    with open(path) as fh:
        lines = fh.read().splitlines()
    for i, line in enumerate(lines):
        if re.match(rf"\s*{re.escape(key)}\s*=", line):
            lines[i] = f"{key}={value}"
            break
    else:
        lines.append(f"{key}={value}")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


ROOT = read_env(".")
TLD = ROOT.get("TLD", "")
ARR = read_env("arr")
AK = read_env("authentik")
USER = AK.get("ADMIN_USERNAME", "")
PASSWORD = AK.get("ADMIN_PASSWORD", "")
EMAIL = AK.get("ADMIN_EMAIL", "")  # asked for by setup.sh


def host_setting(key, default=""):
    """A value from the gitignored host.env, the way setup.sh reads it."""
    try:
        with open(os.path.join(REPO, "host.env")) as fh:
            for line in fh:
                m = re.match(rf"\s*{re.escape(key)}\s*=\s*(.*)$", line)
                if m:
                    return m.group(1).split("#", 1)[0].strip().strip("\"'")
    except OSError:
        pass
    return default


# setup.sh remembers whether authentik is part of this install. Every account
# and login this script configures uses the authentik admin credentials, so
# without it there is nothing to wire — the services are still published at
# <name>.$TLD, just with whatever login of their own they have.
AUTHENTIK = os.environ.get("AUTHENTIK_ENABLED", host_setting("AUTHENTIK_INSTALL", "yes")) != "no"


# --- docker -----------------------------------------------------------------
def docker(*args, check=False):
    return subprocess.run(["docker", *args], capture_output=True, text=True, check=check)


def running(name):
    r = docker("inspect", "-f", "{{.State.Running}}", name)
    return r.returncode == 0 and r.stdout.strip() == "true"


def address(name):
    """The container's address on app-bridge (or its only network)."""
    r = docker("inspect", name)
    if r.returncode != 0:
        return None
    info = json.loads(r.stdout)[0]
    if info["HostConfig"].get("NetworkMode") == "host":
        return "127.0.0.1"  # Plex: on the host network, so this host's localhost
    nets = info["NetworkSettings"]["Networks"]
    if NETWORK in nets and nets[NETWORK].get("IPAddress"):
        return nets[NETWORK]["IPAddress"]
    for n in nets.values():
        if n.get("IPAddress"):
            return n["IPAddress"]
    return None


def compose(stack, *args):
    return subprocess.run(["docker", "compose", *args], cwd=os.path.join(REPO, stack),
                          capture_output=True, text=True)


# --- http -------------------------------------------------------------------
class HttpError(Exception):
    def __init__(self, status, body, url):
        super().__init__(f"HTTP {status} from {url}: {body[:300]}")
        self.status, self.body = status, body


class Api:
    """A JSON API at base, with fixed headers (an API key, usually)."""

    def __init__(self, base, headers=None, timeout=60):
        self.base, self.headers, self.timeout = base.rstrip("/"), dict(headers or {}), timeout
        self.opener = urllib.request.build_opener(
            urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))

    def call(self, method, path, body=None, form=None, headers=None, raw=False):
        url = self.base + path
        hdrs = {"Accept": "application/json", **self.headers, **(headers or {})}
        data = None
        if form is not None:
            data = urllib.parse.urlencode(form, doseq=True).encode()
            hdrs["Content-Type"] = "application/x-www-form-urlencoded"
        elif body is not None:
            data = json.dumps(body).encode()
            hdrs["Content-Type"] = "application/json"
        req = urllib.request.Request(url, data=data, method=method, headers=hdrs)
        try:
            with self.opener.open(req, timeout=self.timeout) as resp:
                text = resp.read().decode("utf-8", "replace")
                if raw:
                    return text
                return json.loads(text) if text.strip() else None
        except urllib.error.HTTPError as e:
            raise HttpError(e.code, e.read().decode("utf-8", "replace"), url) from None

    def get(self, path, **kw):
        return self.call("GET", path, **kw)

    def post(self, path, body=None, **kw):
        return self.call("POST", path, body, **kw)

    def put(self, path, body=None, **kw):
        return self.call("PUT", path, body, **kw)


def wait_for(name, port, path="/", timeout=180, ok=(200, 401, 403)):
    """Wait until the container answers HTTP on port; return its base URL."""
    if not running(name):
        return None
    deadline = time.time() + timeout
    while time.time() < deadline:
        ip = address(name)
        if ip:
            base = f"http://{ip}:{port}"
            try:
                with urllib.request.urlopen(base + path, timeout=5) as r:
                    if r.status in ok:
                        return base
            except urllib.error.HTTPError as e:
                if e.code in ok:
                    return base
            except (urllib.error.URLError, OSError):
                pass
        time.sleep(3)
    warn(f"{name} is running but did not answer on :{port} within {timeout}s — skipped")
    return None


def section(title, needs=()):
    """Decorator: run fn(**bases) under a heading once its containers answer."""
    def wrap(fn):
        def run():
            missing = [n for n, _p, _path in needs if not running(n)]
            if missing:
                return  # stack not deployed here: nothing to wire, nothing to say
            say(title)
            bases = {}
            for name, port, path in needs:
                base = wait_for(name, port, path)
                if not base:
                    return
                bases[name.replace("-", "_")] = base
            try:
                fn(**bases)
            except HttpError as e:
                warn(f"{title}: {e}")
            except Exception as e:  # keep going with the next app
                warn(f"{title}: {type(e).__name__}: {e}")
        run.__name__ = fn.__name__
        STEPS.append(run)
        return run
    return wrap


STEPS = []


def fill(schema_item, **values):
    """A copy of an *arr schema entry with the given fields set."""
    item = json.loads(json.dumps(schema_item))
    for f in item.get("fields", []):
        if f["name"] in values:
            f["value"] = values[f["name"]]
    return item


def field(item, name):
    for f in item.get("fields", []):
        if f["name"] == name:
            return f.get("value")
    return None


def quality_leaves(items):
    """Every leaf quality in a quality profile's item tree."""
    for item in items:
        if item.get("quality") is not None:
            yield item
        elif item.get("items"):
            yield from quality_leaves(item["items"])


# --- Transmission -----------------------------------------------------------
@section("Transmission", needs=[("transmission", 9091, "/transmission/web/")])
def transmission(transmission):
    rpc = transmission + "/transmission/rpc"

    def call(method, args=None):
        sid = ""
        for _ in range(2):
            req = urllib.request.Request(rpc, method="POST", data=json.dumps(
                {"method": method, "arguments": args or {}}).encode(),
                headers={"X-Transmission-Session-Id": sid, "Content-Type": "application/json"})
            try:
                with urllib.request.urlopen(req, timeout=20) as r:
                    return json.load(r)["arguments"]
            except urllib.error.HTTPError as e:
                if e.code != 409:
                    raise
                sid = e.headers.get("X-Transmission-Session-Id", "")
        raise RuntimeError("no Transmission session id")

    # Both seed goals are 0: Transmission pauses a torrent the moment it is
    # complete, which is what Sonarr and Radarr require before they will remove
    # it ("Remove Completed" only removes a stopped torrent). With a non-zero
    # goal the torrent keeps seeding, Sonarr/Radarr move on, and it sits there
    # at 100% for good. Nothing is seeded with 0 — raise these if you need a
    # private tracker's ratio.
    want = {"download-dir": "/data/downloads/torrents",
            "incomplete-dir": "/data/downloads/incomplete",
            "incomplete-dir-enabled": True,
            "idle-seeding-limit-enabled": True,
            "idle-seeding-limit": 0,
            "seedRatioLimited": True,
            "seedRatioLimit": 0}
    cur = call("session-get")
    change = {k: v for k, v in want.items() if cur.get(k) != v}
    if change:
        call("session-set", change)
        note("downloads to /data/downloads/torrents, in progress to .../incomplete; "
             "seed goals at 0 so a finished torrent stops at once and is removed")
    else:
        note("download directories and seed goals already set")


# --- Plex -------------------------------------------------------------------
# Before Sonarr and Radarr, so a server claimed just now gets its connection
# from them on this same run.
def plex_token():
    prefs = os.path.join(REPO, "plex/config/plex/Library/Application Support/Plex Media Server/Preferences.xml")
    try:
        m = re.search(r'PlexOnlineToken="([^"]+)"', open(prefs).read())
        return m.group(1) if m else ""
    except OSError:
        return ""


@section("Plex", needs=[("plex", 32400, "/identity")])
def plex(plex):
    token = plex_token()
    if not token and sys.stdin.isatty():
        # Claiming ties the server to your Plex account. The code is only valid
        # for four minutes, which is why it is asked for now — with Plex
        # running — and not by setup.sh before you deploy it.
        code = input("    Plex claim code from https://plex.tv/claim (Enter to skip): ").strip()
        if code:
            # The image claims itself at start when PLEX_CLAIM is set.
            set_env("plex", "PLEX_CLAIM", code)
            r = compose("plex", "up", "-d", "--force-recreate", "plex")
            if r.returncode != 0:
                warn(f"could not restart Plex with the claim code: {r.stderr.strip()[:200]}")
            for _ in range(40):
                token = plex_token()
                if token:
                    break
                time.sleep(3)
            # Single-use and expired either way: never leave it lying around.
            set_env("plex", "PLEX_CLAIM", "")
            if token:
                note("claimed to your Plex account")
                wait_for("plex", 32400, "/identity")
            else:
                warn("Plex did not claim itself — the code may have expired; get a new one and re-run")
    if not token:
        note("not claimed — run ./integrations.py with a code from https://plex.tv/claim")
        return
    # Plex is on the host network; from here it is localhost.
    api = Api("http://127.0.0.1:32400", {"X-Plex-Token": token})
    have = {loc["path"] for d in api.get("/library/sections").get("MediaContainer", {}).get("Directory", [])
            for loc in d.get("Location", [])}
    for name, kind, agent, scanner, path in (
            ("Movies", "movie", "tv.plex.agents.movie", "Plex Movie", "/data/downloads/movies"),
            ("TV Shows", "show", "tv.plex.agents.series", "Plex TV Series", "/data/downloads/tv")):
        if path in have:
            note(f"library {name} exists")
            continue
        q = urllib.parse.urlencode({"name": name, "type": kind, "agent": agent, "scanner": scanner,
                                    "language": "en-US", "location": path})
        api.call("POST", "/library/sections?" + q, raw=True)
        note(f"library {name}: {path}")
    # Plex only turns a queued library update into a real scan when one of its
    # own scan settings is on. With both off, the connection Sonarr and Radarr
    # get below is accepted and then dropped, so new imports show up only after
    # a manual "Scan Library Files" — turn automatic and hourly scanning on.
    prefs = urllib.parse.urlencode({
        "FSEventLibraryUpdatesEnabled": 1,
        "FSEventLibraryPartialScanEnabled": 1,
        "ScheduledLibraryUpdatesEnabled": 1,
        "ScheduledLibraryUpdateInterval": 3600,
    })
    api.call("PUT", "/:/prefs?" + prefs, raw=True)
    note("library scanning: on file changes (partial) and hourly")


# --- Sonarr and Radarr ------------------------------------------------------
def wire_arr(api, kind):
    tv = kind == "sonarr"
    library = "/data/downloads/tv" if tv else "/data/downloads/movies"
    drop = "/data/downloads/torrents/tv" if tv else "/data/downloads/torrents/movies"

    if not any(r["path"].rstrip("/") == library for r in api.get("/rootfolder")):
        api.post("/rootfolder", {"path": library})
        note(f"root folder {library}")
    else:
        note(f"root folder {library} exists")

    # "Unmonitor Deleted Episodes" / "Unmonitor Deleted Movies": deleting
    # something from Plex removes the file, the next disk scan sees it is gone
    # and the app stops monitoring it, instead of searching for it and pulling
    # it back down.
    media = api.get("/config/mediamanagement")
    flag = "autoUnmonitorPreviouslyDownloadedEpisodes" if tv else "autoUnmonitorPreviouslyDownloadedMovies"
    if not media.get(flag):
        media[flag] = True
        api.put("/config/mediamanagement", media)
        note("unmonitor deleted: on (a Plex delete is not downloaded again)")
    else:
        note("unmonitor deleted already on")

    # The built-in "HD - 720p/1080p" profile is what everything is added with,
    # and Remux-1080p is switched off in it: a 1080p remux is several times the
    # size of a Bluray/WEB 1080p and is not wanted here. Setting the profile on
    # the import lists is what makes it the default for automatically added
    # media (there is no server-wide "default profile" setting in the apps).
    profile = next((p for p in api.get("/qualityprofile") if p["name"] == "HD - 720p/1080p"), None)
    if profile is None:
        note('quality profile "HD - 720p/1080p" missing — profiles left alone')
    else:
        remuxes = [q for q in quality_leaves(profile["items"])
                   if "1080" in q["quality"]["name"] and "remux" in q["quality"]["name"].lower()]
        if any(q["allowed"] for q in remuxes):
            for q in remuxes:
                q["allowed"] = False
            api.put(f"/qualityprofile/{profile['id']}", profile)
            note(f'quality profile {profile["name"]}: Remux-1080p off')
        else:
            note(f'quality profile {profile["name"]}: Remux-1080p already off')
        for il in api.get("/importlist"):
            if il.get("qualityProfileId") != profile["id"]:
                il["qualityProfileId"] = profile["id"]
                api.put(f"/importlist/{il['id']}", il)
                note(f'import list {il["name"]}: quality profile -> {profile["name"]}')

    if not any(c["implementation"] == "Transmission" for c in api.get("/downloadclient")):
        schema = next(s for s in api.get("/downloadclient/schema") if s["implementation"] == "Transmission")
        # A directory, not a category. Transmission has labels of its own, but
        # Sonarr and Radarr refuse a Category and a Directory at the same time,
        # and the directory is what keeps TV and movies in separate drop folders.
        client = fill(schema, host="transmission", port=9091, urlBase="/transmission/",
                      **({"tvDirectory": drop, "tvCategory": ""} if tv
                         else {"movieDirectory": drop, "movieCategory": ""}))
        client.update(name="Transmission", enable=True, priority=1,
                      removeCompletedDownloads=True, removeFailedDownloads=True)
        api.post("/downloadclient", client)
        note(f"download client: Transmission, into {drop}")
    else:
        note("download client Transmission exists")

    token = plex_token()
    if not token:
        note("Plex not claimed yet — no Plex connection (added once it is)")
    elif not any(n["implementation"] == "PlexServer" for n in api.get("/notification")):
        schema = next(s for s in api.get("/notification/schema") if s["implementation"] == "PlexServer")
        conn = fill(schema, host="plex", port=32400, useSsl=False, authToken=token, updateLibrary=True)
        conn["name"] = "Plex"
        for k in list(conn):
            # Every "on <event>" this app supports: imports, upgrades, renames, deletes.
            if k.startswith("on") and isinstance(conn[k], bool) and conn.get("supports" + k[0].upper() + k[1:], True):
                conn[k] = True
        # forceSave: saving tests the connection, and Plex may still be starting.
        api.post("/notification?forceSave=true", conn)
        note("connection: Plex (library updates on import)")
    else:
        note("Plex connection exists")


@section("Sonarr", needs=[("sonarr", 8989, "/ping")])
def sonarr(sonarr):
    wire_arr(Api(sonarr + "/api/v3", {"X-Api-Key": ARR["SONARR_API_KEY"]}), "sonarr")


@section("Radarr", needs=[("radarr", 7878, "/ping")])
def radarr(radarr):
    wire_arr(Api(radarr + "/api/v3", {"X-Api-Key": ARR["RADARR_API_KEY"]}), "radarr")


# --- Prowlarr ---------------------------------------------------------------
# The public trackers station runs that still have a definition and answer;
# the ones marked True go through Byparr to get past Cloudflare.
PUBLIC_INDEXERS = [
    ("1337x", True), ("thepiratebay", False), ("yts", False), ("eztv", True),
    ("limetorrents", False), ("torrentdownloads", True), ("torrentdownload", False),
    ("noname-club", False), ("bigfangroup", False),
]


@section("Prowlarr", needs=[("prowlarr", 9696, "/ping")])
def prowlarr(prowlarr):
    api = Api(prowlarr + "/api/v1", {"X-Api-Key": ARR["PROWLARR_API_KEY"]})

    tags = {t["label"]: t["id"] for t in api.get("/tag")}
    if "byparr" not in tags:
        tags["byparr"] = api.post("/tag", {"label": "byparr"})["id"]
    byparr_tag = tags["byparr"]

    if not any(p["implementation"] == "FlareSolverr" for p in api.get("/indexerProxy")):
        schema = next(s for s in api.get("/indexerProxy/schema") if s["implementation"] == "FlareSolverr")
        proxy = fill(schema, host="http://byparr:8191/", requestTimeout=180)
        proxy.update(name="Byparr", tags=[byparr_tag])
        api.post("/indexerProxy?forceSave=true", proxy)
        note("indexer proxy: Byparr (for indexers tagged byparr)")
    else:
        note("Byparr proxy exists")

    apps = {a["implementation"] for a in api.get("/applications")}
    for impl, port, key in (("Sonarr", 8989, "SONARR_API_KEY"), ("Radarr", 7878, "RADARR_API_KEY")):
        if impl in apps:
            note(f"app {impl} exists")
            continue
        schema = next(s for s in api.get("/applications/schema") if s["implementation"] == impl)
        app = fill(schema, prowlarrUrl="http://prowlarr:9696",
                   baseUrl=f"http://{impl.lower()}:{port}", apiKey=ARR[key])
        app.update(name=impl, syncLevel="fullSync", enable=True)
        api.post("/applications?forceSave=true", app)
        note(f"app {impl}: full sync, so it gets every indexer below")

    if not any(c["implementation"] == "Transmission" for c in api.get("/downloadclient")):
        schema = next(s for s in api.get("/downloadclient/schema") if s["implementation"] == "Transmission")
        client = fill(schema, host="transmission", port=9091, urlBase="/transmission/")
        client.update(name="Transmission", enable=True, priority=1)
        api.post("/downloadclient?forceSave=true", client)
        note("download client: Transmission (for grabs made in Prowlarr itself)")

    have = {i.get("definitionName") for i in api.get("/indexer")}
    todo = [(d, via) for d, via in PUBLIC_INDEXERS if d not in have]
    if todo:
        schemas = {s.get("definitionName"): s for s in api.get("/indexer/schema")}
        profile = api.get("/appprofile")[0]["id"]
        for definition, via_byparr in todo:
            schema = schemas.get(definition)
            if not schema:
                warn(f"indexer {definition}: no longer a Prowlarr definition — skipped")
                continue
            ix = json.loads(json.dumps(schema))
            ix.update(enable=True, appProfileId=profile, priority=25,
                      tags=[byparr_tag] if via_byparr else [])
            try:
                # forceSave: a tracker that is down today is still worth having.
                api.post("/indexer?forceSave=true", ix)
                note(f"indexer {schema['name']}" + (" (via Byparr)" if via_byparr else ""))
            except HttpError as e:
                warn(f"indexer {definition}: {e}")
        api.post("/command", {"name": "ApplicationIndexerSync"})
    else:
        note("public indexers exist")


# --- Bazarr -----------------------------------------------------------------
def bazarr_key():
    try:
        text = open(os.path.join(REPO, "arr/config/bazarr/config/config.yaml")).read()
    except OSError:
        return ""
    m = re.search(r"^auth:\n(?:  .*\n)*?  apikey: (\S+)", text, re.M)
    return m.group(1).strip("'\"") if m else ""


@section("Bazarr", needs=[("bazarr", 6767, "/")])
def bazarr(bazarr):
    key = bazarr_key()
    if not key:
        warn("no API key in arr/config/bazarr/config/config.yaml yet — skipped")
        return
    api = Api(bazarr, {"X-API-KEY": key}, timeout=120)
    cur = api.get("/api/system/settings")
    general, s_cfg, r_cfg = cur.get("general", {}), cur.get("sonarr", {}), cur.get("radarr", {})
    form = {}
    if not (general.get("use_sonarr") and s_cfg.get("ip") == "sonarr" and s_cfg.get("apikey") == ARR["SONARR_API_KEY"]):
        form.update({"settings-general-use_sonarr": "true", "settings-sonarr-ip": "sonarr",
                     "settings-sonarr-port": "8989", "settings-sonarr-base_url": "/",
                     "settings-sonarr-ssl": "false", "settings-sonarr-apikey": ARR["SONARR_API_KEY"]})
    if not (general.get("use_radarr") and r_cfg.get("ip") == "radarr" and r_cfg.get("apikey") == ARR["RADARR_API_KEY"]):
        form.update({"settings-general-use_radarr": "true", "settings-radarr-ip": "radarr",
                     "settings-radarr-port": "7878", "settings-radarr-base_url": "/",
                     "settings-radarr-ssl": "false", "settings-radarr-apikey": ARR["RADARR_API_KEY"]})
    if not api.get("/api/system/languages/profiles"):
        # English only. Station's second profile (Russian + English, by tag) is
        # a UI change away: Settings -> Languages.
        form.update({
            "languages-enabled": json.dumps(["en"]),
            "languages-profiles": json.dumps([{
                "profileId": 1, "name": "English", "cutoff": None,
                "items": [{"id": 1, "language": "en", "hi": "False", "forced": "False",
                           "audio_exclude": "False", "audio_only_include": "False"}],
                "mustContain": [], "mustNotContain": [], "originalFormat": 0, "tag": None}]),
            "settings-general-serie_default_enabled": "true", "settings-general-serie_default_profile": "1",
            "settings-general-movie_default_enabled": "true", "settings-general-movie_default_profile": "1",
        })
    if not general.get("enabled_providers"):
        # The ones that need no account. Add OpenSubtitles.com and friends in
        # the UI once you have logins for them.
        form["settings-general-enabled_providers"] = ["embeddedsubtitles", "subf2m", "bsplayer"]
        # Needed for the embeddedsubtitles provider to extract tracks at all.
        form["settings-general-use_embedded_subs"] = "false"
    if form:
        api.call("POST", "/api/system/settings", form=form)
        for what, keys in (("Sonarr", "settings-sonarr-ip"), ("Radarr", "settings-radarr-ip"),
                           ("English language profile (default for series and movies)", "languages-profiles"),
                           ("providers: embedded subtitles, Subf2m, BSPlayer", "settings-general-enabled_providers")):
            if keys in form:
                note(what)
    else:
        note("already connected to Sonarr and Radarr")


# --- Lingarr ----------------------------------------------------------------
@section("Lingarr", needs=[("lingarr", 9876, "/")])
def lingarr(lingarr):
    api = Api(lingarr)
    if api.get("/api/auth/authenticated").get("requiresOnboarding"):
        # Its first-run screen: no login of its own (authentik is in front),
        # and no API key.
        api.post("/api/auth/onboarding", {"enableUserAuth": "false", "enableApiKey": "false"})
        note("first-run setup done (no own login: authentik is in front)")
    keys = ["sonarr_url", "radarr_url"]
    cur = api.post("/api/setting/multiple/get", keys) or {}
    for kind, port, key in (("sonarr", 8989, "SONARR_API_KEY"), ("radarr", 7878, "RADARR_API_KEY")):
        url = f"http://{kind}:{port}"
        if cur.get(f"{kind}_url") == url:
            note(f"{kind.capitalize()} connected")
            continue
        api.post("/api/setting", {"key": f"{kind}_url", "value": url})
        api.post("/api/setting/encrypted", {"key": f"{kind}_api_key", "value": ARR[key]})
        api.post("/api/setting", {"key": f"{kind}_settings_completed", "value": "true"})
        note(f"{kind.capitalize()}: {url} (no languages set: choose them in Lingarr)")


# --- Cleanuparr -------------------------------------------------------------
@section("Cleanuparr", needs=[("cleanuparr", 11011, "/health")])
def cleanuparr(cleanuparr):
    api = Api(cleanuparr)
    status = api.get("/api/auth/status")
    if not status.get("setupCompleted"):
        api.post("/api/auth/setup/account", {"username": USER, "password": PASSWORD})
        api.post("/api/auth/setup/complete", {})
        note(f"account {USER} (same password as authentik)")
    try:
        tokens = api.post("/api/auth/login", {"username": USER, "password": PASSWORD})["tokens"]
    except HttpError:
        warn(f"cannot log in to Cleanuparr as {USER} (password changed there?) — skipped")
        return
    key = Api(cleanuparr, {"Authorization": "Bearer " + tokens["accessToken"]}).get("/api/account/api-key")["apiKey"]
    api = Api(cleanuparr, {"X-Api-Key": key})

    oidc = api.get("/api/account/oidc")
    if not oidc.get("enabled"):
        api.put("/api/account/oidc", {
            "enabled": True, "providerName": "authentik",
            "issuerUrl": f"https://authentik.{TLD}/application/o/cleanuparr/",
            "clientId": "cleanuparr", "clientSecret": AK["CLEANUPARR_OIDC_CLIENT_SECRET"],
            "scopes": "openid profile email", "redirectUrl": f"https://cleanuparr.{TLD}",
            # Not exclusive: the local login stays as the way in while
            # authentik is down.
            "exclusiveMode": False})
        note("login with authentik (OIDC)")
    else:
        note("authentik login already on")

    for kind, port, key_name, version in (("sonarr", 8989, "SONARR_API_KEY", 4), ("radarr", 7878, "RADARR_API_KEY", 6)):
        cfg = api.get(f"/api/configuration/{kind}")
        if cfg.get("instances"):
            note(f"{kind.capitalize()} connected")
            continue
        api.post(f"/api/configuration/{kind}/instances", {
            "enabled": True, "name": kind.capitalize(), "url": f"http://{kind}:{port}",
            "apiKey": ARR[key_name], "version": version})
        note(f"{kind.capitalize()}: http://{kind}:{port}")

    if not api.get("/api/configuration/download_client").get("clients"):
        api.post("/api/configuration/download_client", {
            "enabled": True, "name": "Transmission", "typeName": "transmission", "type": "torrent",
            "host": "http://transmission:9091", "urlBase": "transmission", "username": "", "password": ""})
        note("download client: Transmission")

    # Station's two cleaners: stalled/slow/failed downloads, and the community
    # malware blocklist. Only switched on here; their rules are the UI's.
    for feature, label in (("queue_cleaner", "queue cleaner"), ("malware_blocker", "malware blocker")):
        cfg = api.get(f"/api/configuration/{feature}")
        if cfg.get("enabled"):
            continue
        cfg["enabled"] = True
        if feature == "malware_blocker":
            for kind in ("sonarr", "radarr"):
                if isinstance(cfg.get(kind), dict):
                    cfg[kind].update(enabled=True, blocklistPath="https://cleanuparr.pages.dev/static/blacklist",
                                     blocklistType="blacklist")
        api.put(f"/api/configuration/{feature}", cfg)
        note(f"{label}: on")


# --- Kavita -----------------------------------------------------------------
@section("Kavita", needs=[("kavita", 5000, "/api/health")])
def kavita(kavita):
    api = Api(kavita)
    creds = {"username": USER, "password": PASSWORD}
    if not EMAIL:
        warn("authentik/.env has no ADMIN_EMAIL (Kavita matches your login by it) — run ./setup.sh")
        return
    try:
        me = api.post("/api/Account/login", creds)
    except HttpError:
        try:
            # Only allowed while Kavita has no users at all: the first becomes
            # admin. The email is what the authentik login is matched on.
            me = api.post("/api/Account/register", {**creds, "email": EMAIL})
            note(f"admin account {USER} <{EMAIL}> (same password as authentik)")
        except HttpError as e:
            warn(f"cannot log in to Kavita as {USER}, nor create that account ({e.status}) — skipped")
            return
    auth = Api(kavita, {"Authorization": "Bearer " + me["token"]})

    if read_env("books").get("KAVITA_API_KEY") != me.get("apiKey"):
        set_env("books", "KAVITA_API_KEY", me["apiKey"])
        compose("books", "up", "-d", "books-glue")
        note("API key saved to books/.env for books-glue (restarted)")

    if not auth.get("/api/Library/libraries"):
        auth.post("/api/Library/create", {
            "name": "Books", "type": 2, "folders": ["/data"], "folderWatching": True,
            "includeInDashboard": True, "includeInSearch": True, "manageCollections": True,
            "manageReadingLists": True, "allowScrobbling": False, "fileGroupTypes": [1, 2, 3, 4],
            "excludePatterns": [], "enableMetadata": True, "metadataProvider": 2})
        note("library Books: the Calibre library CWA fills")
    else:
        note("library exists")

    settings = auth.get("/api/Settings")
    if settings.get("oidcConfig", {}).get("enabled"):
        note("authentik login already on")
        return
    settings["hostName"] = f"https://kavita.{TLD}"
    settings["oidcConfig"].update(
        authority=f"https://authentik.{TLD}/application/o/kavita/", clientId="kavita",
        secret=AK["KAVITA_OIDC_CLIENT_SECRET"], enabled=True, providerName="authentik",
        autoLogin=True, provisionAccounts=True, requireVerifiedEmail=False)
    try:
        auth.post("/api/Settings", settings)
        # Kavita only registers its OIDC handler at start: without a restart the
        # login button answers 500 ("no handler for OpenIdConnect").
        docker("restart", "kavita", check=True)
        note("login with authentik (OIDC), straight to it (Kavita restarted)")
    except HttpError as e:
        # Kavita fetches authentik's discovery document before it accepts this:
        # not possible until authentik runs and has its certificate.
        warn(f"Kavita refused the authentik login for now ({e.body[:120]}) — re-run ./setup.sh later")


# --- Shelfmark --------------------------------------------------------------
SHELFMARK = os.path.join(REPO, "books/config/shelfmark/plugins")


def shelfmark_wanted():
    return {
        "prowlarr_config.json": {
            "PROWLARR_ENABLED": True, "PROWLARR_URL": "http://prowlarr:9696",
            "PROWLARR_API_KEY": ARR.get("PROWLARR_API_KEY", "")},
        "prowlarr_clients.json": {
            "PROWLARR_TORRENT_CLIENT": "transmission", "TRANSMISSION_URL": "http://transmission:9091",
            "TRANSMISSION_CATEGORY": "books", "TRANSMISSION_DOWNLOAD_DIR": "/data/downloads/complete/books"},
        # Transmission sees the ingest folder at /data/downloads/complete/books,
        # Shelfmark at /cwa-book-ingest.
        "advanced.json": {
            "PROWLARR_REMOTE_PATH_MAPPINGS": [{"host": "transmission", "remotePath": "/data/downloads/complete/books",
                                               "localPath": "/cwa-book-ingest"}]},
        # The image's "folder" output defaults to /books, a path this container
        # does not mount: the download lands in the container's writable layer
        # and CWA never sees it. Copy into the ingest folder Shelfmark already
        # has at /cwa-book-ingest, which is the same host folder CWA watches.
        "downloads.json": {"BOOKS_OUTPUT_MODE": "folder", "DESTINATION": "/cwa-book-ingest"},
        "security.json": {
            "AUTH_METHOD": "oidc",
            "OIDC_DISCOVERY_URL": f"https://authentik.{TLD}/application/o/shelfmark/.well-known/openid-configuration",
            "OIDC_CLIENT_ID": "shelfmark", "OIDC_CLIENT_SECRET": AK.get("SHELFMARK_OIDC_CLIENT_SECRET", ""),
            "OIDC_SCOPES": ["openid", "email", "profile"], "OIDC_GROUP_CLAIM": "groups",
            "OIDC_ADMIN_GROUP": "authentik Admins", "OIDC_USE_ADMIN_GROUP": True,
            "OIDC_AUTO_PROVISION": True, "OIDC_BUTTON_LABEL": "authentik"},
        # Byparr (the arr stack's, on app-bridge) for the Cloudflare pages of
        # the direct-download mirrors.
        "cloudflare_bypass.json": {
            "USE_CF_BYPASS": True, "USING_EXTERNAL_BYPASSER": True,
            "EXT_BYPASSER_URL": "http://byparr:8191", "EXT_BYPASSER_PATH": "/v1"},
        # The General tab, one folder up: its Library button opens CWA, so the
        # URL is the one your browser uses.
        "../settings.json": {"CALIBRE_WEB_URL": f"https://calibre-web-automated.{TLD}"},
    }


@section("Shelfmark", needs=[("shelfmark", 8084, "/")])
def shelfmark(shelfmark):
    # A local admin first. Shelfmark only turns the OIDC login on when a
    # password admin exists to fall back on (otherwise it quietly stays open to
    # everyone), and this is the moment its API still needs no login.
    try:
        security = json.load(open(os.path.join(SHELFMARK, "security.json")))
    except (OSError, ValueError):
        security = {}
    if security.get("AUTH_METHOD") in (None, "none"):
        if not EMAIL:
            warn("authentik/.env has no ADMIN_EMAIL (Shelfmark matches your login by it) — run ./setup.sh")
            return
        try:
            Api(shelfmark).post("/api/admin/users", {"username": USER, "password": PASSWORD,
                                                     "email": EMAIL, "role": "admin"})
            note(f"admin account {USER} (same password as authentik; the fallback login)")
        except HttpError as e:
            if e.status != 409:  # 409: it exists already
                raise
    # books-glue's mirror refresh logs in as that admin: the settings API it
    # pushes to needs a session once the authentik login is on.
    books = read_env("books")
    if books.get("SHELFMARK_USERNAME") != USER or books.get("SHELFMARK_PASSWORD") != PASSWORD:
        set_env("books", "SHELFMARK_USERNAME", USER)
        set_env("books", "SHELFMARK_PASSWORD", PASSWORD)
        compose("books", "up", "-d", "books-glue")
        note("login for the mirror refresh saved to books/.env for books-glue (restarted)")
    # The rest straight into its settings files rather than its API: once the
    # authentik login is on, the API wants a login session this script does
    # not have. A key already set to something else is left as you set it.
    # Shelfmark writes its switches' defaults (PROWLARR_ENABLED: false, ...) to
    # these files itself, so an off switch is not necessarily yours: each one
    # we want on is turned on once, and remembered here, so that turning it
    # off in the UI afterwards sticks.
    switched_path = os.path.join(SHELFMARK, "..", "integrations-switched.json")
    try:
        switched = set(json.load(open(switched_path)))
    except (OSError, ValueError):
        switched = set()
    changes, wanted = {}, {}
    for name, want in shelfmark_wanted().items():
        path = os.path.normpath(os.path.join(SHELFMARK, name))
        wanted[path] = want
        try:
            cur = json.load(open(path))
        except (OSError, ValueError):
            cur = {}
        add = {k: v for k, v in want.items()
               if k not in cur or cur[k] in ("", None, [], "none")
               or (v is True and cur[k] is False and f"{name}:{k}" not in switched)
               or (name == "downloads.json" and k == "DESTINATION" and cur[k] == "/books")
               or (name == "security.json" and cur.get("AUTH_METHOD") in (None, "none"))}
        if add:
            changes[path] = {**cur, **add}
        switched |= {f"{name}:{k}" for k, v in want.items() if v is True}
    with open(switched_path, "w") as fh:
        json.dump(sorted(switched), fh, indent=2)
    if not changes:
        note("already wired to Prowlarr, Transmission, Byparr, CWA and authentik")
        return
    docker("stop", "shelfmark", check=True)
    try:
        for path, data in changes.items():
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                json.dump(data, fh, indent=2)
            note(f"{os.path.basename(path)}: " + ", ".join(sorted(k for k in data if k in wanted[path])))
    finally:
        docker("start", "shelfmark", check=True)


# --- Calibre-Web-Automated ----------------------------------------------------
def werkzeug_hash(password):
    """What calibre-web's werkzeug.generate_password_hash writes."""
    salt = base64.b64encode(secrets.token_bytes(12)).decode()[:16]
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 600000).hex()
    return f"pbkdf2:sha256:600000${salt}${digest}"


@section("Calibre-Web", needs=[("calibre-web-automated", 8083, "/")])
def calibre_web(calibre_web_automated):
    db = os.path.join(REPO, "books/config/calibre-web-automated/app.db")
    if not os.path.exists(db):
        warn("no app.db yet — skipped")
        return
    con = sqlite3.connect(db)
    try:
        header_on = con.execute("SELECT config_allow_reverse_proxy_header_login, config_reverse_proxy_login_header_name "
                                "FROM settings").fetchone()
        has_user = con.execute("SELECT 1 FROM user WHERE name = ?", (USER,)).fetchone()
        has_default = con.execute("SELECT 1 FROM user WHERE name = 'admin'").fetchone()
    finally:
        con.close()
    need_header = tuple(header_on or ()) != (1, "X-authentik-username")
    need_user = not has_user and has_default
    if not need_header and not need_user:
        note(f"logs in as {USER} through authentik")
        return
    # CWA holds app.db open; change it only while it is stopped.
    docker("stop", "calibre-web-automated", check=True)
    try:
        con = sqlite3.connect(db)
        with con:
            if need_user:
                # The image's default admin/admin123, renamed to your login —
                # that name is what authentik's header logs in as. The password
                # is for OPDS and Kobo sync, which skip authentik.
                con.execute("UPDATE user SET name = ?, password = ?, email = ? WHERE name = 'admin'",
                            (USER, werkzeug_hash(PASSWORD), EMAIL))
                note(f"default admin renamed to {USER}, password as authentik's")
            if need_header:
                con.execute("UPDATE settings SET config_allow_reverse_proxy_header_login = 1, "
                            "config_reverse_proxy_login_header_name = 'X-authentik-username'")
                note("logs in whoever authentik says (X-authentik-username)")
        con.close()
    finally:
        docker("start", "calibre-web-automated", check=True)


# --- Home Assistant ----------------------------------------------------------
HA_CONFIG = os.path.join(REPO, "smarthome/config/homeassistant/configuration.yaml")
# Behind Traefik: without these HA answers every proxied request with 400.
# Traefik reaches it from a Docker network (172.16/12) or this host.
HA_PROXIES = ["127.0.0.1", "::1", "172.16.0.0/12"]
HA_CLIENT = "http://127.0.0.1:8123/"
# Added to configuration.yaml when it has no such section yet:
HA_SECTIONS = {
    # Only for a Home Assistant that still reads http: from YAML; newer ones
    # keep it in .storage/http (see ha_trust_traefik).
    "http": "http:\n  use_x_forwarded_for: true\n  trusted_proxies:\n" + "".join(f"    - {p}\n" for p in HA_PROXIES),
    # History in the smarthome stack's MariaDB (URL from compose.yml).
    "recorder": "recorder:\n  db_url: !env_var RECORDER_DB_URL\n",
}


def ha_token(api):
    """A session for USER: onboarding it as the owner if HA is brand new."""
    try:
        steps = {s["step"]: s["done"] for s in api.get("/api/onboarding")}
    except HttpError as e:
        if e.status != 404:
            raise
        steps = {}  # onboarding finished: HA removes that API afterwards
    if not steps.get("user", True):
        code = api.post("/api/onboarding/users", {
            "client_id": HA_CLIENT, "name": USER, "username": USER,
            "password": PASSWORD, "language": "en"})["auth_code"]
        note(f"owner account {USER} (same password as authentik)")
    else:
        flow = api.post("/auth/login_flow", {"client_id": HA_CLIENT, "handler": ["homeassistant", None],
                                            "redirect_uri": HA_CLIENT})
        res = api.post(f"/auth/login_flow/{flow['flow_id']}",
                       {"username": USER, "password": PASSWORD, "client_id": HA_CLIENT})
        if res.get("type") != "create_entry":
            return None
        code = res["result"]
    tok = api.call("POST", "/auth/token", form={"grant_type": "authorization_code", "code": code,
                                                 "client_id": HA_CLIENT})["access_token"]
    auth = Api(api.base, {"Authorization": "Bearer " + tok})
    # The rest of the first-run wizard, so the UI opens straight onto the
    # dashboard. Location, units and so on are yours to set in Settings.
    for step, body in (("core_config", {}), ("analytics", {}),
                       ("integration", {"client_id": HA_CLIENT, "redirect_uri": HA_CLIENT})):
        if not steps.get(step, True):
            auth.post(f"/api/onboarding/{step}", body)
    return auth


HA_HTTP_EDIT = r"""
import json, sys
path = "/config/.storage/http"
store = json.load(open(path))
stable = store["data"].setdefault("stable", {})
stable["use_x_forwarded_for"] = True
stable["trusted_proxies"] = sorted(set(stable.get("trusted_proxies", [])) | set(sys.argv[1:]))
json.dump(store, open(path, "w"), indent=2)
"""


def ha_trust_traefik():
    """Newer HA keeps its HTTP settings in .storage/http, and imports the YAML
    http: block only once — onboarding creates the file before we could add
    one. So set the two keys there, with HA stopped (it rewrites the file on
    the way down). HA writes it root-only (0600), so it is read through the
    container and edited by a one-off one of the same image."""
    r = docker("exec", "homeassistant", "cat", "/config/.storage/http")
    if r.returncode != 0:
        return None                     # no such file: an HA that reads YAML
    stable = json.loads(r.stdout).get("data", {}).get("stable", {})
    if stable.get("use_x_forwarded_for") and set(HA_PROXIES) <= set(stable.get("trusted_proxies", [])):
        return False
    info = json.loads(docker("inspect", "homeassistant").stdout)[0]
    image = info["Config"]["Image"]
    config = next(m["Source"] for m in info["Mounts"] if m["Destination"] == "/config")
    docker("stop", "homeassistant", check=True)
    try:
        docker("run", "--rm", "--entrypoint", "python3", "-v", f"{config}:/config", image,
               "-c", HA_HTTP_EDIT, *HA_PROXIES, check=True)
    finally:
        docker("start", "homeassistant", check=True)
    return True


@section("Home Assistant", needs=[("homeassistant", 8123, "/api/")])
def homeassistant(homeassistant):
    api = Api(homeassistant)
    auth = ha_token(api)
    if not auth:
        warn(f"cannot log in to Home Assistant as {USER} (password changed there?) — skipped")
        return

    # configuration.yaml: our two sections, only where it has none of its own.
    try:
        text = open(HA_CONFIG).read()
    except OSError:
        text = None
    changed = ha_trust_traefik()
    if changed:
        note("trusts Traefik (its forwarded headers), restarted")
        time.sleep(10)
        api = Api(wait_for("homeassistant", 8123, "/api/") or homeassistant)
        auth = ha_token(api)
    elif changed is False:
        note("trusts Traefik already")
    if text is not None:
        add = [k for k in HA_SECTIONS if not re.search(rf"^{k}:", text, re.M)
               and not (k == "http" and changed is not None)]
        if add:
            with open(HA_CONFIG, "a") as fh:
                fh.write("\n# Added by irabelle-stack's integrations.py\n" + "".join(HA_SECTIONS[k] for k in add))
            docker("restart", "homeassistant", check=True)
            note("configuration.yaml: " + ", ".join(
                {"http": "trusts Traefik", "recorder": "history in MariaDB"}[k] for k in add) + " (restarted)")
            time.sleep(10)  # let it go down before waiting for it to come back
            api = Api(wait_for("homeassistant", 8123, "/api/") or homeassistant)
            auth = ha_token(api)
        else:
            note("configuration.yaml already has its recorder settings")

    # MQTT, with the smarthome stack's login.
    sh = read_env("smarthome")
    if not running("mqtt") or not sh.get("MQTT_PASSWORD"):
        return
    if auth.get("/api/config/config_entries/entry?domain=mqtt"):
        note("MQTT connected")
        return
    flow = auth.post("/api/config/config_entries/flow", {"handler": "mqtt", "show_advanced_options": False})
    res = auth.post(f"/api/config/config_entries/flow/{flow['flow_id']}", {
        "broker": "127.0.0.1", "port": 1883, "protocol": "5",
        "username": sh.get("MQTT_USER", "mqtt"), "password": sh["MQTT_PASSWORD"],
        # The form's collapsed "advanced" section: required, and so are its two
        # certificate switches — plain MQTT on this host, so both off.
        "other_settings": {"set_client_cert": False, "set_ca_cert": "off"}})
    if res.get("type") == "create_entry":
        note("MQTT: Mosquitto at 127.0.0.1:1883")
    else:
        fields = [f.get("name") for f in flow.get("data_schema", [])]
        warn(f"MQTT not added (form fields {fields}): {json.dumps(res)[:200]}")


def main():
    if not TLD:
        warn(".env has no TLD — nothing wired")
        return 0
    if not AUTHENTIK:
        warn("authentik is disabled (AUTHENTIK_INSTALL=no): every account and login")
        warn("this script configures uses its admin credentials, so there is nothing")
        warn("to wire. The services are still published at <name>.$TLD — run")
        warn("./setup.sh --authentik to turn single sign-on back on, or wire the")
        warn("apps by hand.")
        return 0
    if not (USER and PASSWORD):
        warn("authentik/.env has no ADMIN_USERNAME/ADMIN_PASSWORD — run ./setup.sh")
        return 0
    if not all(ARR.get(k) for k in ("SONARR_API_KEY", "RADARR_API_KEY", "PROWLARR_API_KEY")) and running("sonarr"):
        warn("arr/.env is missing API keys — run ./setup.sh first")
        return 0
    for step in STEPS:
        step()
    return 0


if __name__ == "__main__":
    sys.exit(main())
